name: "The One Pipeline: Split"

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # renovate: datasource=crate depName=cargo-deny versioning=semver
  CARGO_DENY_VERSION: 0.14.20
  # renovate: datasource=crate depName=grcov versioning=semver
  GRCOV_VERSION: 0.8.19
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: 8.15.6

jobs:
  backend:
    runs-on: ubuntu-22.04
    env:
      JOBS: 1 # See https://git.io/vdao3 for details.
      RUSTDOCFLAGS: "-D warnings"
      RUST_BACKTRACE: 1
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost/postgres
      RUSTFLAGS: "-D warnings -Cinstrument-coverage"
      MALLOC_CONF: "background_thread:true,abort_conf:true,abort:true,junk:true"

    services:
      postgres:
        image: postgres:13@sha256:eee22204934b36935237e7c92355e3178cfdf3c5377dec9c19c848115cc4637b
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - run: cargo fmt --check --all
      - run: cargo clippy --all-targets --all-features --workspace
      - run: cargo doc --no-deps --document-private-items

      - run: cargo build --tests --workspace
      - run: cargo test --workspace

      - run: curl -sL https://github.com/mozilla/grcov/releases/download/v${{ env.GRCOV_VERSION }}/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar xjf -
      - run: rustup component add llvm-tools
      - run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" --ignore "target/debug/build/**" -o target/coverage.lcov

  frontend:
    runs-on: ubuntu-22.04
    env:
      JOBS: 1 # See https://git.io/vdao3 for details.

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache: pnpm
          node-version-file: package.json

      - run: pnpm install

      - run: pnpm lint:hbs
      #- run: pnpm lint:js
      - run: pnpm lint:deps
      - run: pnpm prettier:check
      - run: pnpm test-coverage
